/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiBadRequestResponse struct {

	Errors []ErrorModel `json:"errors,omitempty"`

	StatusCode int32 `json:"statusCode,omitempty"`

	Message string `json:"message,omitempty"`
}
