/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ErrorModel struct {

	ErrorCode int32 `json:"errorCode,omitempty"`

	HelpUrl string `json:"helpUrl,omitempty"`

	Message string `json:"message,omitempty"`
}
