/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ContentTypeModel struct for ContentTypeModel
type ContentTypeModel struct {
	Title string `json:"title,omitempty"`
	Name string `json:"name,omitempty"`
	FileExtension *string `json:"fileExtension,omitempty"`
}
