/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MessageDataTypes the model 'MessageDataTypes'
type MessageDataTypes string

// List of MessageDataTypes
const (
	EMBEDDED MessageDataTypes = "Embedded"
	FILE_REFERENCE MessageDataTypes = "FileReference"
)
