/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// FileReference struct for FileReference
type FileReference struct {
	Host string `json:"host,omitempty"`
	Bucket string `json:"bucket,omitempty"`
	File string `json:"file,omitempty"`
}
