/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ApiBadRequestResponse struct for ApiBadRequestResponse
type ApiBadRequestResponse struct {
	Errors []ErrorModel `json:"errors,omitempty"`
	StatusCode int32 `json:"statusCode,omitempty"`
	Message string `json:"message,omitempty"`
}
