/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// EndpointTypes the model 'EndpointTypes'
type EndpointTypes string

// List of EndpointTypes
const (
	HTTP EndpointTypes = "HTTP"
	RTMP EndpointTypes = "RTMP"
	KAFKA EndpointTypes = "Kafka"
	G_RPC EndpointTypes = "gRPC"
)
