/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ErrorModel struct for ErrorModel
type ErrorModel struct {
	ErrorCode int32 `json:"errorCode,omitempty"`
	HelpUrl *string `json:"helpUrl,omitempty"`
	Message *string `json:"message,omitempty"`
}
