/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RetryStrategies the model 'RetryStrategies'
type RetryStrategies string

// List of RetryStrategies
const (
	SIMPLE RetryStrategies = "Simple"
	RETRY_TOPICS RetryStrategies = "RetryTopics"
	STATEFUL_ORDERED RetryStrategies = "StatefulOrdered"
	STATEFUL_UNORDERED RetryStrategies = "StatefulUnordered"
)
